# Generated by Django 3.1.1 on 2020-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='prescription_validity',
            new_name='prescription_end_date',
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='start_date',
            field=models.DateField(),
        ),
    ]
