# Generated by Django 3.1.1 on 2020-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0002_auto_20200926_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='prescription_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_end_date',
        ),
        migrations.AddField(
            model_name='prescription',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
