# Generated by Django 3.1.1 on 2020-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0003_auto_20200926_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdisease',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
