# Generated by Django 3.0.10 on 2020-09-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0004_auto_20200926_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnostic_question',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
