# Generated by Django 3.0.10 on 2020-09-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0005_prescription_diagnostic_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=60)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_s_api.Patient')),
            ],
        ),
    ]
