# Generated by Django 3.0.10 on 2020-09-27 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0006_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
