# Generated by Django 3.0.10 on 2020-09-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0007_measure_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=60)),
                ('unit', models.CharField(choices=[('Kg', 'Kilograms'), ('cm', 'Centimeters'), ('mmHg', 'Millimeters of Mercury'), ('mg/dL', 'Millograms per deciliter')], default='', max_length=60, null=True)),
                ('date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_s_api.Patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
