# Generated by Django 3.0.10 on 2020-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0008_auto_20200927_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='type',
            field=models.CharField(choices=[('Height', 'Height'), ('Weight', 'Weight'), ('BloodPreassure', 'Blood preassure'), ('Glicata', 'Glicata'), ('n.a.', 'Undefined')], default='n.a.', max_length=60),
        ),
    ]
