# Generated by Django 3.0.10 on 2020-09-28 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0009_auto_20200927_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.CharField(default='a8098c1a-f86e-11da-bd1a-00112444be1e', max_length=60),
            preserve_default=False,
        ),
    ]
