# Generated by Django 3.0.10 on 2020-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0010_auto_20200928_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdisease',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
