# Generated by Django 3.0.10 on 2020-09-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0011_auto_20200928_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='deleted_on',
        ),
    ]
