# Generated by Django 3.0.10 on 2020-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0013_patient_deleted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
