# Generated by Django 3.0.10 on 2020-09-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0016_auto_20200928_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='drug_interaction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='precautions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
