# Generated by Django 3.0.10 on 2020-09-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0017_auto_20200929_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='name',
            new_name='generic_name',
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacter_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
