# Generated by Django 3.0.10 on 2020-09-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0019_auto_20200929_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_interactions',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='precautions',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
