# Generated by Django 3.0.10 on 2020-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0020_auto_20200929_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
    ]
