# Generated by Django 3.0.10 on 2020-09-30 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ehr_s_api', '0021_auto_20200930_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(default='INFO', max_length=2000, null=True)),
                ('message', models.CharField(max_length=2000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr_s_api.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
